# sintax=docker/dockerfile:1
FROM oraclelinux:8-slim AS builder

ARG BUILD_MODE BUILD_VERSION ARCH RPM_ARCH

RUN <<EOT
  # database dependencies
  microdnf -y install \
    compat-libgfortran-48 \
    glibc \
    glibc-devel \
    libaio \
    libgcc \
    libnsl \
    libstdc++ \
    xz \
  ;

  # runtime dependencies
  microdnf -y install \
    zip \
    unzip \
    gzip \
    less \
    findutils \
    vim-minimal \
    sudo \
    zstd \
  ;

  # build dependencies
  microdnf -y install \
    bc \
    binutils \
    compat-openssl10 \
    elfutils-libelf \
    file \
    hostname \
    ksh \
    make \
    passwd \
    procps-ng \
    smartmontools \
    sysstat \
  ;
EOT

# https://download.oracle.com/otn-pub/otn_software/db-free/oracle-database-free-23ai-23.8-1.el8.x86_64.rpm
RUN --mount=source=oracle-database-free-23ai-23.9-1.el8.x86_64.rpm,target=oracle.rpm <<EOT
  rpm -iv --nodeps oracle.rpm
EOT

ENV ORACLE_BASE=/opt/oracle
ENV ORACLE_HOME=/opt/oracle/product/23ai/dbhomeFree
ENV ORACLE_BASE_CONFIG=/opt/oracle/product/23ai/dbhomeFree
ENV ORACLE_BASE_HOME=/opt/oracle/product/23ai/dbhomeFree
ENV ORACLE_SID=FREE
ENV PATH=${PATH}:/opt/oracle/product/23ai/dbhomeFree/bin:/opt/oracle
# ENV NLS_LANG=.AL16UTF16

COPY configureDatabase.sh /install/
RUN /install/configureDatabase.sh

COPY install.${BUILD_VERSION}.sh container-entrypoint.sh resetPassword createAppUser createDatabase healthcheck.sh /install/
RUN /install/install.${BUILD_VERSION}.sh "${BUILD_MODE}"

##########################################################################################
FROM scratch AS os_layer

# Redefine environment variables, etc. as we copied everything from an empty image (scratch)
ENV ORACLE_BASE=/opt/oracle
ENV ORACLE_HOME=/opt/oracle/product/23ai/dbhomeFree
ENV ORACLE_BASE_CONFIG=/opt/oracle/product/23ai/dbhomeFree
ENV ORACLE_BASE_HOME=/opt/oracle/product/23ai/dbhomeFree
ENV ORACLE_SID=FREE
ENV PATH=${PATH}:/opt/oracle/product/23ai/dbhomeFree/bin:/opt/oracle
# ENV NLS_LANG=.AL16UTF16

COPY --from=builder / /

RUN chown root "${ORACLE_HOME}"/bin/extjob; \
    chmod 4750 "${ORACLE_HOME}"/bin/extjob; \
    chown root "${ORACLE_HOME}"/rdbms/admin/externaljob.ora; \
    chmod 640 "${ORACLE_HOME}"/rdbms/admin/externaljob.ora; \
    chown root "${ORACLE_HOME}"/bin/jssu; \
    chmod 4750 "${ORACLE_HOME}"/bin/jssu

LABEL org.opencontainers.image.title="Oracle Database Free Container images"
LABEL org.opencontainers.image.description="Oracle Database Free for everyone!"
LABEL org.opencontainers.image.authors="Gerald Venzl"
LABEL org.opencontainers.image.source=https://github.com/gvenzl/oci-oracle-free
LABEL org.opencontainers.image.licenses=Apache-2.0
LABEL org.opencontainers.image.documentation=https://github.com/gvenzl/oci-oracle-free/blob/main/README.md

USER oracle
WORKDIR ${ORACLE_BASE}

HEALTHCHECK CMD "${ORACLE_BASE}"/healthcheck.sh >/dev/null || exit 1

ENTRYPOINT ["container-entrypoint.sh"]
