#
# Since: September, 2023
# Author: gvenzl
# Name: Dockerfile.23
# Description: Dockerfile to build Oracle Database 23 Free
#
# Copyright 2023 Gerald Venzl
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

FROM oraclelinux:8-slim AS builder

ARG BUILD_MODE BUILD_VERSION DB_FLAVOR ARCH RPM_ARCH

ENV OCI_IMAGE_VERSION=${BUILD_VERSION} \
    OCI_IMAGE_FLAVOR=${BUILD_MODE} \
    ORACLE_BASE=/opt/oracle \
    ORACLE_BASE_CONFIG=/opt/oracle/product/23${DB_FLAVOR}/dbhomeFree \
    ORACLE_BASE_HOME=/opt/oracle/product/23${DB_FLAVOR}/dbhomeFree \
    ORACLE_HOME=/opt/oracle/product/23${DB_FLAVOR}/dbhomeFree \
    ORACLE_SID=FREE \
    PATH=${PATH}:/opt/oracle/product/23${DB_FLAVOR}/dbhomeFree/bin:/opt/oracle
    # NLS_LANG=.AL16UTF16

RUN <<EOT
  # database dependencies
  microdnf -y install \
    compat-libgfortran-48 \
    glibc \
    glibc-devel \
    libaio \
    libgcc \
    libnsl \
    libstdc++ \
    xz \
  ;

  # runtime dependencies
  microdnf -y install \
    zip \
    unzip \
    gzip \
    less \
    findutils \
    vim-minimal \
    sudo \
    zstd \
  ;

  # build dependencies
  microdnf -y install \
    bc \
    binutils \
    compat-openssl10 \
    elfutils-libelf \
    file \
    hostname \
    ksh \
    make \
    passwd \
    procps-ng \
    smartmontools \
    sysstat \
  ;
EOT

RUN <<EOT
  package=oracle-database-free-23ai-23.8-1.el8.x86_64.rpm
  curl -sLO https://download.oracle.com/otn-pub/otn_software/db-free/"$package"
  rpm -iv --nodeps "$package"
  rm "$package"
EOT

COPY configureDatabase.sh /install/
RUN /install/configureDatabase.sh

COPY install.${BUILD_VERSION}.sh container-entrypoint.sh resetPassword createAppUser createDatabase healthcheck.sh /install/
RUN /install/install.${BUILD_VERSION}.sh "${BUILD_MODE}"

##########################################################################################
FROM scratch AS os_layer

ARG DB_FLAVOR

# Redefine environment variables, etc. as we copied everything from an empty image (scratch)
ENV ORACLE_BASE=/opt/oracle \
    ORACLE_BASE_CONFIG=/opt/oracle/product/23${DB_FLAVOR}/dbhomeFree \
    ORACLE_BASE_HOME=/opt/oracle/product/23${DB_FLAVOR}/dbhomeFree \
    ORACLE_HOME=/opt/oracle/product/23${DB_FLAVOR}/dbhomeFree \
    ORACLE_SID=FREE \
    PATH=${PATH}:/opt/oracle/product/23${DB_FLAVOR}/dbhomeFree/bin:/opt/oracle
    # NLS_LANG=.AL16UTF16

COPY --from=builder / /

RUN chown root "${ORACLE_HOME}"/bin/extjob; \
    chmod 4750 "${ORACLE_HOME}"/bin/extjob; \
    chown root "${ORACLE_HOME}"/rdbms/admin/externaljob.ora; \
    chmod 640 "${ORACLE_HOME}"/rdbms/admin/externaljob.ora; \
    chown root "${ORACLE_HOME}"/bin/jssu; \
    chmod 4750 "${ORACLE_HOME}"/bin/jssu

LABEL org.opencontainers.image.title="Oracle Database Free Container images"
LABEL org.opencontainers.image.description="Oracle Database Free for everyone!"
LABEL org.opencontainers.image.authors="Gerald Venzl"
LABEL org.opencontainers.image.source=https://github.com/gvenzl/oci-oracle-free
LABEL org.opencontainers.image.licenses=Apache-2.0
LABEL org.opencontainers.image.documentation=https://github.com/gvenzl/oci-oracle-free/blob/main/README.md

USER oracle
WORKDIR ${ORACLE_BASE}

HEALTHCHECK CMD "${ORACLE_BASE}"/healthcheck.sh >/dev/null || exit 1

ENTRYPOINT ["container-entrypoint.sh"]
